export const insertQuery = `INSERT INTO TEST (
     Invoice_Type, Name, Invoice_date, Invoice_#, Stage, Company, Responsible_person,
    Products, Amount_Currency, Amount, Currency, Contact, Customer, Created_on, Updated_by,
    Updated_on, Created_by, Available_to_everyone, Sales_Date, Created_by_CRM_form, Moved_by,
    Moved_on, Previous_stage, Your_company_details, Source, Source_information, Deals, Estimates,
    Pay_before, Project, Sales_Amount, Sales_Base_of_the_Commission, Title_Deed_Amount, Seller,
    Project_Sales_Company, Invoice_Company_Contact, Total_Commission_without_VAT, Customer_Downpayment_Date,
    Service_Fee_Due_Date, Commission_Rate, VAT_Rate, Account_Manager, Seller_Total_Commission_without_VAT,
    Location, Property_Type, Seller_Invoice_Amount_without_VAT, Seller_Commission_VAT_Amount,
    Seller_Commission_with_VAT, Buyer_Total_Commission_without_VAT, Buyer_Invoice_Amount_without_VAT,
    Buyer_Commission_VAT_Amount, Buyer_Commission_with_VAT, Corporate_Tax, Total_VAT,
    Total_Distributed_Commision, Net_Income, Commission_Calculation_Base_Amount, Deal_Responsible,
    Deal_Responsible_Commission, Viewing_Responsible, Viewing_Responsible_Commission, Deal_Office_Manager,
    Deal_Office_Manager_Commission, Viewing_Office_Manager_1, Viewing_Office_Manager_1_Commission,
    Viewing_Office_Manager_2, Viewing_Office_Manager_2_Commission, Viewing_Office_Manager_3,
    Viewing_Office_Manager_3_Commission, Viewing_Office_Manager_4, Viewing_Office_Manager_4_Commission,
    Viewing_Office_Manager_5, Viewing_Office_Manager_5_Commission, Viewing_Office_Manager_6,
    Viewing_Office_Manager_6_Commission, Assistant_Office_Manager_1, Assistant_Office_Manager_1_Commission,
    Assistant_Office_Manager_2, Assistant_Office_Manager_2_Commission, Assistant_Office_Manager_3,
    Assistant_Office_Manager_3_Commission, Assistant_Office_Manager_4, Assistant_Office_Manager_4_Commission,
    Assistant_Office_Manager_5, Assistant_Office_Manager_5_Commission, Assistant_Office_Manager_6,
    Assistant_Office_Manager_6_Commission, Portfolio_Supervisor, Portfolio_Supervisor_Commission,
    Lead_Partner, Lead_Partner_Commission_without_VAT, Lead_Partner_Invoice_Amount_without_VAT, Listing_Partner,
    Listing_Partner_Commission_without_VAT, Listing_Partner_Invoice_Amount_without_VAT, Partner_Manager,
    Partner_Manager_Commission, Partner_Supervisor, Partner_Supervisor_Commission, Responsible_Lawyer,
    Lawyer_Commission, Partner_Lawyer, Partner_Lawyer_Commission_without_VAT, Partner_Lawyer_Invoice_Amount_without_VAT,
    After_Sales_Responsible, After_Sales_Responsible_Commission, Administration_Pool, Operations_Local_Portal_Pool,
    Trade_Management_Pool, Sales_Expenses, Group_Company, Group_Company_Share, Commission_Due_Date,
    Seller_Scanned_Invoice, Buyer_Scanned_Invoice, Payment_Method, Sold_Property_Reference_Number,
    Location_Country, Location_Province, Location_District, Location_Neighborhood, Main_Language,
    Secondary_Language, Third_Language, Nationality, Country_of_Residence, Deposit_Payment_Method,
    Deposit_Payment_Date, Deposit_Amount, Sales_Office, Selling_Office_Country, Sales_Currency,
    After_Sales_SPA_ID, Responsible_Lawyer_Commission_Rate, RL_Fixed_Commission_Amount, VISA_DR_Commission_Rate,
    VISA_DR_Fixed_Commission_Amount, Is_AP_exist, Downpayment_WF_is_running, Waiting_Downpayment,
    Downpayment_Received, Invoice_Agreed, Invoice_Sent, Commission_Received, All_Commissions_Paid, 
    Sales_Cancelled, Received_Commission_Amount, Received_Commission_Currency, Received_Currency_Exchange_Rate,
    Received_Commission_Amount_in_TRY, First_name, Last_name,CRM_URL_ID_1,
    Citizenship_ID, Product_ID, Project_Name, Invoice_Company_ID, Company_name, Last_name_contact_card,
    Tax_ID, CRM_URL_ID_2, Name_Last_Name, Responsible_Person_ID, Responsible_Person_Name,
    Responsible_Person_Office, Responsible_Person_Office_Name, Source_2, Nationality_M, Country_of_Residance_M,
    Main_Language_M, Lead_Create, Pasaport_Number, TC_ID_or_Tax_Number, Contact_Kart_URL, Deal_Link_URL
  ) VALUES (
     @Invoice_Type, @Name, @Invoice_date, @Invoice_#, @Stage, @Company, @Responsible_person,
    @Products, @Amount_Currency, @Amount, @Currency, @Contact, @Customer, @Created_on, @Updated_by,
    @Updated_on, @Created_by, @Available_to_everyone, @Sales_Date, @Created_by_CRM_form, @Moved_by,
    @Moved_on, @Previous_stage, @Your_company_details, @Source, @Source_information, @Deals, @Estimates,
    @Pay_before, @Project, @Sales_Amount, @Sales_Base_of_the_Commission, @Title_Deed_Amount, @Seller,
    @Project_Sales_Company, @Invoice_Company_Contact, @Total_Commission_without_VAT, @Customer_Downpayment_Date,
    @Service_Fee_Due_Date, @Commission_Rate, @VAT_Rate, @Account_Manager, @Seller_Total_Commission_without_VAT,
    @Location, @Property_Type, @Seller_Invoice_Amount_without_VAT, @Seller_Commission_VAT_Amount,
    @Seller_Commission_with_VAT, @Buyer_Total_Commission_without_VAT, @Buyer_Invoice_Amount_without_VAT,
    @Buyer_Commission_VAT_Amount, @Buyer_Commission_with_VAT, @Corporate_Tax, @Total_VAT,
    @Total_Distributed_Commision, @Net_Income, @Commission_Calculation_Base_Amount, @Deal_Responsible,
    @Deal_Responsible_Commission, @Viewing_Responsible, @Viewing_Responsible_Commission, @Deal_Office_Manager,
    @Deal_Office_Manager_Commission, @Viewing_Office_Manager_1, @Viewing_Office_Manager_1_Commission,
    @Viewing_Office_Manager_2, @Viewing_Office_Manager_2_Commission, @Viewing_Office_Manager_3,
    @Viewing_Office_Manager_3_Commission, @Viewing_Office_Manager_4, @Viewing_Office_Manager_4_Commission,
    @Viewing_Office_Manager_5, @Viewing_Office_Manager_5_Commission, @Viewing_Office_Manager_6,
    @Viewing_Office_Manager_6_Commission, @Assistant_Office_Manager_1, @Assistant_Office_Manager_1_Commission,
    @Assistant_Office_Manager_2, @Assistant_Office_Manager_2_Commission, @Assistant_Office_Manager_3,
    @Assistant_Office_Manager_3_Commission, @Assistant_Office_Manager_4, @Assistant_Office_Manager_4_Commission,
    @Assistant_Office_Manager_5, @Assistant_Office_Manager_5_Commission, @Assistant_Office_Manager_6,
    @Assistant_Office_Manager_6_Commission, @Portfolio_Supervisor, @Portfolio_Supervisor_Commission,
    @Lead_Partner, @Lead_Partner_Commission_without_VAT, @Lead_Partner_Invoice_Amount_without_VAT, @Listing_Partner,
    @Listing_Partner_Commission_without_VAT, @Listing_Partner_Invoice_Amount_without_VAT, @Partner_Manager,
    @Partner_Manager_Commission, @Partner_Supervisor, @Partner_Supervisor_Commission, @Responsible_Lawyer,
    @Lawyer_Commission, @Partner_Lawyer, @Partner_Lawyer_Commission_without_VAT, @Partner_Lawyer_Invoice_Amount_without_VAT,
    @After_Sales_Responsible, @After_Sales_Responsible_Commission, @Administration_Pool, @Operations_Local_Portal_Pool,
    @Trade_Management_Pool, @Sales_Expenses, @Group_Company, @Group_Company_Share, @Commission_Due_Date,
    @Seller_Scanned_Invoice, @Buyer_Scanned_Invoice, @Payment_Method, @Sold_Property_Reference_Number,
    @Location_Country, @Location_Province, @Location_District, @Location_Neighborhood, @Main_Language,
    @Secondary_Language, @Third_Language, @Nationality, @Country_of_Residence, @Deposit_Payment_Method,
    @Deposit_Payment_Date, @Deposit_Amount, @Sales_Office, @Selling_Office_Country, @Sales_Currency,
    @After_Sales_SPA_ID, @Responsible_Lawyer_Commission_Rate, @RL_Fixed_Commission_Amount, @VISA_DR_Commission_Rate,
    @VISA_DR_Fixed_Commission_Amount, @Is_AP_exist, @Downpayment_WF_is_running, @Waiting_Downpayment,
    @Downpayment_Received, @Invoice_Agreed, @Invoice_Sent, @Commission_Received, @All_Commissions_Paid, 
    @Sales_Cancelled, @Received_Commission_Amount, @Received_Commission_Currency, @Received_Currency_Exchange_Rate,
    @Received_Commission_Amount_in_TRY, @First_name, @Last_name, @CRM_URL_ID_1,
    @Citizenship_ID, @Product_ID, @Project_Name, @Invoice_Company_ID, @Company_name, @Last_name_contact_card,
    @Tax_ID, @CRM_URL_ID_2, @Name_Last_Name, @Responsible_Person_ID, @Responsible_Person_Name,
    @Responsible_Person_Office, @Responsible_Person_Office_Name, @Source_2, @Nationality_M, @Country_of_Residance_M,
    @Main_Language_M, @Lead_Create, @Pasaport_Number, @TC_ID_or_Tax_Number, @Contact_Kart_URL, @Deal_Link_URL
  )`;
